// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcjhxbzysijyujjkvkhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jamh4Ynp5c2lqeXVqamt2a2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMzAzODYsImV4cCI6MjA1NTcwNjM4Nn0.tzX_-u2YYFwUsS855zrGhPgTrtEjqCpgbHlnNh5mySM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);